[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
invest_in_sol = "HC3woQjXDRRA91VsoGit6SZz2CzcAeKHE4BbagYFWUWr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
